// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_NglGpY1ZE8ipet_agtNKnCiiHKW8czc',
    appId: '1:728624760415:web:e772c36c7c2adb9ac67dea',
    messagingSenderId: '728624760415',
    projectId: 'chat-app-fc0c2',
    authDomain: 'chat-app-fc0c2.firebaseapp.com',
    storageBucket: 'chat-app-fc0c2.firebasestorage.app',
    measurementId: 'G-DPWHXJTM7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAys0jJJk7Ov_KVwTBmso1owQWnY8FVmv4',
    appId: '1:728624760415:android:5f0a24dc3e7c0366c67dea',
    messagingSenderId: '728624760415',
    projectId: 'chat-app-fc0c2',
    storageBucket: 'chat-app-fc0c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgRTHXqRZn2Q9_bqPSySK2py0YkPh0ZQ4',
    appId: '1:728624760415:ios:28f810883ac6e7a9c67dea',
    messagingSenderId: '728624760415',
    projectId: 'chat-app-fc0c2',
    storageBucket: 'chat-app-fc0c2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgRTHXqRZn2Q9_bqPSySK2py0YkPh0ZQ4',
    appId: '1:728624760415:ios:28f810883ac6e7a9c67dea',
    messagingSenderId: '728624760415',
    projectId: 'chat-app-fc0c2',
    storageBucket: 'chat-app-fc0c2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_NglGpY1ZE8ipet_agtNKnCiiHKW8czc',
    appId: '1:728624760415:web:3aa0d372016cb2b3c67dea',
    messagingSenderId: '728624760415',
    projectId: 'chat-app-fc0c2',
    authDomain: 'chat-app-fc0c2.firebaseapp.com',
    storageBucket: 'chat-app-fc0c2.firebasestorage.app',
    measurementId: 'G-Z6Z3EFRB44',
  );

}